name: Release

on:
  workflow_dispatch:
    inputs:
      pypi:
        type: boolean
        default: false
      draft:
        type: boolean
        default: true
      prerelease:
        type: boolean
        default: true

permissions:
  contents: write

jobs:
  check-version:
    runs-on: [ubuntu-22.04]

    steps:
      - uses: actions/checkout@v2

      - name: Get package version
        working-directory: packages/tree_clipper/
        id: get_package_version
        run: |
          PACKAGE_VERSION=$(yq '.project.version' pyproject.toml)
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> "$GITHUB_OUTPUT"

      - name: Get addon version
        working-directory: packages/tree_clipper_addon/src/tree_clipper_addon
        id: get_addon_version
        run: |
          ADDON_VERSION=$(yq '.version' blender_manifest.toml)
          echo "ADDON_VERSION=$ADDON_VERSION" >> "$GITHUB_OUTPUT"

      - name: Check if versions match
        env:
          PACKAGE_VERSION: ${{ steps.get_package_version.outputs.PACKAGE_VERSION }}
          ADDON_VERSION: ${{ steps.get_addon_version.outputs.ADDON_VERSION }}
        run: |
          GIT_VERSION="${GITHUB_REF##refs/tags/v}"
          if [[ "$PACKAGE_VERSION" != "$GIT_VERSION" ]]; then
            echo "Version mismatch! Package: $PACKAGE_VERSION, Git: $GIT_VERSION"
            exit 1
          fi
          if [[ "$ADDON_VERSION" != "$GIT_VERSION" ]]; then
            echo "Version mismatch! Addon: $ADDON_VERSION, Git: $GIT_VERSION"
            exit 1
          fi
          echo "Versions match"
        continue-on-error: ${{ github.event.inputs.draft == 'true' }}

  build-package:
    if: ${{ github.event.inputs.pypi == 'true' }}
    needs: [check-version]
    uses: ./.github/workflows/build-package.yml

  publish-package:
    if: ${{ github.event.inputs.pypi == 'true' }}
    needs: [build-package]
    runs-on: [ubuntu-22.04]
    environment: pypi
    permissions:
      id-token: write  # required for Trusted Publishing
    steps:
      - name: Download dists
        uses: actions/download-artifact@v4
        with:
          name: tree-clipper-package
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  bundle-extension:
    needs: [check-version]
    uses: ./.github/workflows/bundle-extension.yml

  release-extension:
    needs: [bundle-extension]
    runs-on: [ubuntu-22.04]
    steps:
      - uses: actions/checkout@v2

      - name: Clear release directory
        run: rm -rf release

      - uses: actions/download-artifact@v4
        with:
          name: tree-clipper-extension
          path: release/

      - name: Collect release files into a list
        id: filelist
        run: |
          {
            echo 'release_files<<EOF'
            find release -maxdepth 1 -type f -printf '%p\n'
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: ${{ github.event.inputs.draft }}
          prerelease: ${{ github.event.inputs.prerelease }}
          body_path: CHANGELOG.md
          files: ${{ steps.filelist.outputs.release_files }}
          generate_release_notes: true
          fail_on_unmatched_files: true
          tag_name: ${{ (github.event.inputs.draft == 'true') && format('draft-{0}', github.run_id) || github.ref_name }}
          target_commitish: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}